# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f030b8f145376879a7f2ed5fb60b8f09377fd5d242c343962b4881adbc20e436a97d66a064f742314ba22bb1e2a308314ed1f78bdc564fb5f7e363d5a49b393

test:
  secret_key_base: 5634de4431d3f9f7a31f29f1b2089f100ff2ecbb3799ede19b1bbfb5e9d2dc0b44c6bfb8798839b8ee0e2c09b1cee003274b811bd2f9c739dacdda0c31621fe8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
